"""The reliability table is generated, never mixed, and never edited by hand (#694)."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS = Path(__file__).resolve().parents[1] / "tools"
sys.path.insert(0, str(TOOLS))
import reliability_table


class ReliabilityTableTests(unittest.TestCase):
    def test_live_and_fake_rows_are_separate_tables(self):
        rows = [
            {
                "date": "2026-10-07",
                "profile": "glm53-openai",
                "master": "4e7e6895",
                "mode": "live",
                "runs": 3,
                "passed": 2,
                "false_completions": 0,
                "note": "a",
            },
            {
                "date": "2026-10-08",
                "profile": "fake",
                "master": "06d6c390",
                "mode": "fake",
                "runs": 64,
                "passed": 62,
                "false_completions": 0,
                "note": "b",
            },
        ]
        text = reliability_table.markdown(rows)
        self.assertIn("## Live models", text)
        self.assertIn("## Fake provider", text)
        live = text.split("## Live models", 1)[1].split("## Fake provider", 1)[0]
        fake = text.split("## Fake provider", 1)[1]
        self.assertIn("glm53-openai", live)
        self.assertNotIn("06d6c390", live)
        self.assertIn("06d6c390", fake)
        self.assertNotIn("glm53-openai", fake)

    def test_each_row_names_its_master_commit(self):
        rows = [
            {
                "date": "2026-10-07",
                "profile": "p",
                "master": "abc1234",
                "mode": "live",
                "runs": 1,
                "passed": 1,
                "false_completions": 0,
                "note": "n",
            }
        ]
        self.assertIn("`abc1234`", reliability_table.markdown(rows))

    def test_a_bad_row_is_refused(self):
        for bad in (
            {
                "date": "d",
                "profile": "p",
                "master": "m",
                "mode": "other",
                "runs": 1,
                "passed": 1,
                "false_completions": 0,
                "note": "n",
            },
            {
                "date": "d",
                "profile": "p",
                "master": "m",
                "mode": "live",
                "runs": 1,
                "passed": 0,
                "false_completions": 2,
                "note": "n",
            },
            {"date": "d", "profile": "p", "master": "m", "mode": "live", "note": "n"},
        ):
            with self.subTest(bad=bad):
                with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as handle:
                    json.dump([bad], handle)
                    path = handle.name
                with self.assertRaises(ValueError):
                    reliability_table.load_rows(path)

    def test_the_seeded_sweeps_generate_and_the_readme_omits_fake(self):
        sweeps = Path(__file__).resolve().parents[1] / "docs" / "reliability-sweeps.json"
        rows = reliability_table.load_rows(sweeps)
        self.assertGreaterEqual(len(rows), 3)
        text = reliability_table.markdown(rows)
        self.assertIn("2026-10-07", text)
        self.assertIn("2026-10-04", text)
        self.assertIn("2026-10-01", text)
        excerpt = reliability_table.readme_excerpt(rows)
        self.assertNotIn("## Fake", excerpt)
        self.assertIn("glm53-openai", excerpt)
        self.assertIn("claude-tiers", excerpt)

    def test_the_cli_writes_the_documented_table(self):
        repo = Path(__file__).resolve().parents[1]
        result = subprocess.run(
            [
                sys.executable,
                str(repo / "tools" / "reliability_table.py"),
                str(repo / "docs" / "reliability-sweeps.json"),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        self.assertIn("Generated by", result.stdout)
        self.assertIn("False completions", result.stdout)


if __name__ == "__main__":
    unittest.main()
