// Generated by build-app.sh — the default Autocode checkout baked at build time.
// Overridable at runtime in the app's Settings; regenerated on every build.
enum BuildConfig {
    static let defaultCheckout = "/Users/ankurkothari/Documents/workspace/autocode"
}
