"""Operator-declared prerequisites, checked before paid phase dispatch.

This is readiness, never test proof. Dispatch calls guard with the exact worker
launch context under its existing locks. This module alone writes the
task_preflight record; the public status view only projects it. Commands are
trusted operator inputs, never generated by a model or inferred from a suite.
"""
from __future__ import annotations

try:
    from . import autocode_source_scope as source_scope
except ImportError:
    import autocode_source_scope as source_scope


import copy
import json
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import uuid

try:
    from . import autocode_input_preflight as inputs, autocode_util as util
    from . import autocode_verify as verify, autocode_launch_inputs as launch_inputs
    from . import autocode_runner_check as runner_check
    from . import autocode_preflight_contract as contract, autocode_preflight_worker as workers
    from . import autocode_preflight_design as design
except ImportError:
    import autocode_input_preflight as inputs, autocode_util as util
    import autocode_verify as verify, autocode_launch_inputs as launch_inputs
    import autocode_runner_check as runner_check
    import autocode_preflight_contract as contract, autocode_preflight_worker as workers
    import autocode_preflight_design as design

PHASES = ("planning", "build", "validate")


def load(path):
    """Normalize an explicit manifest; refuse unknown fields and empty checks."""
    body = json.loads(Path(path).read_text())
    if not isinstance(body, dict) or type(body.get("version")) is not int or body["version"] not in (1, 2):
        raise ValueError("Task preflight requires a version 1 or 2 object")
    if set(body) - {"version", "inputs", "runtime_files", "checks", *(['design'] if body['version'] == 2 else [])}:
        raise ValueError("Unknown task preflight manifest fields")
    declared, errors = inputs.validate_inputs(body.get("inputs", []))
    if errors:
        raise ValueError("; ".join(errors))
    files = body.get("runtime_files", [])
    if not isinstance(files, list) or any(not isinstance(p, str) or not p or (not Path(p).is_absolute()
            and (body['version'] == 1 or '..' in Path(p).parts)) for p in files):
        raise ValueError("Task preflight runtime_files must be absolute paths (or project-relative paths in version 2)")
    checks, seen = [], set()
    if not isinstance(body.get("checks"), list) or not body["checks"]:
        raise ValueError("Task preflight requires at least one prerequisite check")
    for row in body["checks"]:
        row = contract.validate_check(row, body['version'])
        ident = row.get("id")
        if not isinstance(ident, str) or not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}", ident) or ident in seen:
            raise ValueError("Task preflight check IDs must be unique safe names")
        seen.add(ident)
        argv = row.get("argv")
        if (row.get("phase") not in PHASES or not isinstance(argv, list) or not argv
                or any(not isinstance(arg, str) or not arg or "\x00" in arg for arg in argv)
                or not isinstance(row.get("recovery"), str) or not row["recovery"].strip()
                or not isinstance(row.get("reuse", True), bool)):
            raise ValueError(f"Invalid prerequisite {ident}: phase, argv and bounded recovery are required")
        checks.append({**row, "reuse": row.get("reuse", True)})
    normalized = {"version": body['version'], "inputs": declared, "runtime_files": sorted(set(files)), "checks": checks}
    if body['version'] == 2:
        normalized['design'] = design.validate(body.get('design'))
    return {"manifest_hash": util.digest(normalized), "body": normalized}


def configure(state, settings, args):
    """Retain the complete manifest; replace only at its own reconciled pause."""
    path = getattr(args, "task_preflight", None)
    if not path:
        return settings
    selected = getattr(args, "_task_preflight_input", None) or load(path)
    previous = settings.get("task_preflight")
    if previous == selected:
        return settings
    if state.get("settings"):
        if not getattr(args, "resume_paused", False) or state.get("status") != "PAUSED_TASK_PREFLIGHT":
            raise ValueError("Changing task preflight requires its stopped PAUSED_TASK_PREFLIGHT boundary and --resume-paused")
        if any(state.get(key) for key in ("active_stage", "pending_report_repair", "uncertain_artifacts", "active_runner_check", "runner_check")):
            raise ValueError("Reconcile active or uncertain work before changing task preflight")
        state.setdefault("user_events", []).append({"kind": "task_preflight_changed", "actor": "user_cli",
            "at": util.now(), "previous": copy.deepcopy(previous), "current": copy.deepcopy(selected)})
    settings["task_preflight"] = selected
    return settings


def phase_for(stage):
    if stage in ("terra", "orchestrator"):
        return "build"
    if stage in ("sol", "astra_checkpoint", "astra_review", "completion", "review_change"):
        return "validate"
    return "planning"


def _file_identity(path):
    target = Path(path)
    if not target.is_file():
        raise ValueError(f"Required prerequisite file is unavailable: {path}")
    stat = target.stat()
    return {"path": str(target.resolve()), "sha256": util.file_hash(target), "mode": stat.st_mode & 0o777,
            "size": stat.st_size, "mtime_ns": stat.st_mtime_ns, "ctime_ns": stat.st_ctime_ns}


def _command(check, root, python):
    # Replace only documented tokens, not arbitrary braces in Python/JS code.
    return [arg.replace("{python}", python).replace("{workspace}", str(root))
            .replace("{runtime}", str(Path(__file__).resolve().parent)) for arg in check["argv"]]


def _proof_commands(state, workspace, checks):
    """Refuse a declared named-proof setup paired with an aggregate-only gate."""
    if not any(check.get('contract', {}).get('kind') == 'proof' for check in checks):
        return
    options = state['settings'].get('regression') or {}
    commands = [options[key] for key in ('test_command', 'regression_command') if options.get(key)]
    if not commands:
        return  # Future test source may determine the command; no invented default.
    framework = verify.detect_framework(workspace, python=options.get('python') or verify.python_for(workspace))
    for command in commands:
        if not verify.expects_results(framework, command):
            raise ValueError('Approved verification command cannot supply the named results required by this proof contract: '
                + command + '; obtain an explicit command correction, preserving the approved suite and test policy')


def _binding(state, workspace, config, checks, worker=None):
    settings = state["settings"]
    python = verify.python_for(workspace)
    environment = verify.test_environment(workspace)
    executables = []
    for check in checks:
        name = _command(check, workspace, python)[0]
        command_env = worker['environment'] if check.get('execution') == 'worker' and worker else environment
        executable = (str(Path(workspace) / name) if "/" in name and not Path(name).is_absolute()
                      else shutil.which(name, path=command_env.get("PATH", '')))
        if not executable:
            raise ValueError(f"Prerequisite {check['id']} executable is unavailable: {name}")
        executables.append(_file_identity(executable))
    # Readiness reuse covers these observable bindings, not unobservable OS
    # permissions or remote services. Such probes must explicitly use reuse=false.
    runtime = {str(p.relative_to(Path(__file__).parent)): util.file_hash(p)
               for p in Path(__file__).parent.rglob("*") if p.suffix in ('.py', '.cjs', '.mjs') and "__pycache__" not in p.parts}
    packages = []
    # Installed dependency changes commonly leave project Git content untouched.
    for lib in sorted({Path(workspace) / ".venv/lib", Path(workspace) / "venv/lib", Path(python).parent.parent / "lib"}):
        for p in sorted(lib.glob("python*/site-packages/*.dist-info/RECORD")):
            packages.append(_file_identity(p))
    source_revision = source_scope.snapshot(workspace, state)["revision"]
    bound = {"manifest": config["manifest_hash"], "source": source_revision,
        "runtime": runtime, "python": _file_identity(python), "python_version": sys.version,
        "packages": packages, "environment_hash": util.digest(environment), "executables": executables,
        "runtime_files": [_file_identity(Path(workspace) / p) for p in config["body"]["runtime_files"]],
        "inputs": [_file_identity(Path(workspace) / row["path"]) for row in config["body"]["inputs"]],
        "routes": {k: settings.get(k) for k in ("roles", "engine", "provider", "transport_identity", "joint_planning")},
        "commands": settings.get("regression"), "limits": settings.get("limits"),
        "design_manifest": (settings.get("design_manifest") or {}).get("manifest_hash"),
        "contract_hash": (state.get("goal_contract") or {}).get("hash"),
        "worker": workers.identity(worker, workspace) if config['body'].get('design') or any(c.get('execution') == 'worker' for c in checks) else None}
    identity = {"runtime_root": str(Path(__file__).resolve().parent), "runtime_sources_hash": util.digest(runtime),
        "controller_python": sys.executable, "controller_python_version": sys.version,
        "test_python": python, "test_python_identity": bound["python"], "source_revision": source_revision,
        "package_record_hash": util.digest(packages), "environment_hash": bound["environment_hash"],
        "required_runtime_files": bound["runtime_files"], "provider_routes_hash": util.digest(bound["routes"]),
        "provider_sandbox_attested": False, "worker": bound['worker']}
    return util.digest(bound), identity


def guard(state, workspace, run_dir, *, worker=None, persist=lambda _path, _state: None):
    """Check this phase before any provider admission. Never writes proof fields.

    Uses the verification engine's source copy, linked dependencies, environment
    scrubbing and process cleanup. Run output is retained beneath this run only.
    A failed readiness result is always rerun after an explicit resume.
    """
    config = state.get("settings", {}).get("task_preflight")
    if not config:
        return
    pause_requested = lambda: (Path(run_dir) / 'pause-requested').exists()
    if pause_requested():
        raise util.Paused('PAUSED_REQUESTED', 'Pause requested before prerequisite execution')
    body = config["body"]
    if config["manifest_hash"] != util.digest(body):
        raise util.Paused("PAUSED_TASK_PREFLIGHT", "Saved prerequisite manifest identity changed; reconcile it before dispatch")
    phase = phase_for(state.get("next_stage"))
    checks = [row for row in body["checks"] if row["phase"] == phase]
    previous = state.get("task_preflight") or {}
    errors, receipts, source_before, design_receipts = [], [], None, []
    directory = Path(run_dir) / "preflight" / uuid.uuid4().hex
    binding, identity = None, None
    try:
        ignored = launch_inputs.supply(state, workspace, run_dir)
        if ignored and ignored.unverified:
            raise ValueError("; ".join(ignored.unverified))
        binding, identity = _binding(state, workspace, config, checks, worker)
        binding = util.digest([binding, ignored.identity if ignored else None])
        if (previous.get("status") == "READY" and previous.get("phase") == phase
                and previous.get("binding") == binding and all(row["reuse"] for row in checks)):
            path = Path(previous["receipt"])
            if path.is_file() and util.file_hash(path) == previous.get("receipt_sha256"):
                return
        directory.mkdir(parents=True, exist_ok=True)
        source_before = source_scope.snapshot(workspace, state)
        changes = verify.changed_files(workspace, source_before["head"])
        needs_copy = bool(checks or body['inputs'] or body.get('design') or
            (body['version'] == 2 and (state['settings'].get('figma_file') or state['settings'].get('design_manifest'))))
        tree = directory / "scratch" / "candidate" if needs_copy else None
        if tree:
            verify.make_tree(workspace, source_before["head"], tree, workspace, changes, dependencies_from=state.get("project_workspace") or workspace, ignored_inputs=ignored)
        try:
            inventory = inputs.check_inputs(workspace, tree, body["inputs"]) if tree else {'errors': []}
            errors.extend(inventory["errors"])
            if not errors:
                _proof_commands(state, workspace, checks)
            if not errors and body['version'] == 2:
                design_receipts = design.check(state['settings'], body.get('design'), workspace, tree, body['inputs'], phase=phase)
                if design_receipts:
                    public = Path(body['design']['manifest']).parent
                    manifest = design.design.load(Path(workspace) / body['design']['manifest'])
                    paths = sorted({str(public / case['artifacts']['screenshot']['path']) for case in manifest['body']['cases']}
                        | {path for row in design_receipts for path in row['context_parts']}
                        | {path for row in body['design']['cases'] for path in row['assets']})
                    for context, root in (('workspace', Path(workspace)), ('scratch', tree)):
                        for index, path in enumerate(paths):
                            output = directory / f'design-{context}-{index}.log'
                            summary = f'{phase}: design access ({context}): {path}'
                            with runner_check.track(state, run_dir, 'task_preflight', summary, persist) as update:
                                update(summary, output=output)
                                result = workers.read_file(worker, root / path, root, output, python=verify.python_for(workspace),
                                    paused=lambda: (Path(run_dir) / 'pause-requested').exists())
                            receipts.append({'id': 'design-access', 'context': context, 'path': path, **result})
                            if result['exit_code'] != 0:
                                raise ValueError(f'{path}: worker design access failed; restore the approved export or correct its access policy; log={output}')
            if not errors:
                timeout = state["settings"].get("limits", {}).get("tool_timeout_seconds", verify.DEFAULT_TIMEOUT)
                for check in checks:
                    for context, root in (("workspace", Path(workspace)), ("scratch", tree)):
                        command = shlex.join(_command(check, root, verify.python_for(workspace)))
                        output = directory / f"{check['id']}-{context}.log"
                        summary = f"{phase}: {check['id']} ({context})"
                        with runner_check.track(state, run_dir, "task_preflight", summary, persist) as update:
                            update(summary, command=command, output=output)
                            before_probe = source_scope.snapshot(root, state)["revision"]
                            if check.get('execution') == 'worker':
                                result, result_text = workers.execute(worker, _command(check, root, verify.python_for(workspace)),
                                    root, output, timeout=check['timeout_seconds'], paused=lambda: (Path(run_dir) / 'pause-requested').exists())
                            elif body['version'] == 2:
                                result = workers.run(_command(check, root, verify.python_for(workspace)), root, output,
                                    timeout=check['timeout_seconds'], environment=verify.test_environment(root),
                                    paused=lambda: (Path(run_dir) / 'pause-requested').exists())
                                result_text = output.read_text(errors='replace')
                            else:
                                result = verify.run_command(command, root, output, timeout=timeout or 120)
                                output = Path(result['output'])
                                result_text = output.read_text(errors='replace')
                        receipts.append({"id": check["id"], "context": context, **result})
                        if pause_requested():
                            errors.append('Pause requested during prerequisite execution')
                        if source_scope.snapshot(root, state)["revision"] != before_probe:
                            errors.append(f"{check['id']} ({context}): prerequisite changed source; inspect it before resuming")
                        if result["exit_code"] != 0 or result["timed_out"]:
                            errors.append(f"{check['id']} ({context}): prerequisite command failed; {check['recovery']}; log={output}")
                        if not errors:
                            try:
                                detail = contract.check_result(check, result_text, state)
                                if detail:
                                    receipts[-1]['readiness'] = detail
                            except (ValueError, TypeError, KeyError) as error:
                                errors.append(f"{check['id']} ({context}): {error}; {check['recovery']}; log={output}")
                        if errors:
                            break
                    if errors:
                        break
        finally:
            if tree:
                verify.remove_tree(workspace, tree)
        if source_scope.snapshot(workspace, state)["revision"] != source_before["revision"]:
            errors.append("Prerequisite command changed source files; preserve the changes and inspect the command before resuming")
        after_ignored = launch_inputs.supply(state, workspace, run_dir)
        if after_ignored and after_ignored.unverified:
            errors.extend(after_ignored.unverified)
        if not errors and util.digest([_binding(state, workspace, config, checks, worker)[0], after_ignored.identity if after_ignored else None]) != binding:
            errors.append("Prerequisite runtime or configuration changed during checks; inspect it and resume for a fresh check")
    except (OSError, ValueError, TypeError, KeyError, RuntimeError, subprocess.SubprocessError) as error:
        errors.append(f"Prerequisite setup: {error}; correct the declared input/runtime and resume this run")
    if identity and not errors:
        checked = bool(design_receipts) or any(c.get('execution') == 'worker' for c in checks)
        identity['worker_permissions_checked'] = checked
        identity['provider_sandbox_attested'] = checked and worker['engine'] == 'codex'
    record = {"kind": "prerequisite", "execution_context": "declared_per_check" if body['version'] == 2 else "runner_test_environment", "phase": phase,
        "execution_identity": identity,
        "status": "BLOCKED" if errors else "READY", "checked_at": util.now(), "binding": binding,
        "manifest_hash": config["manifest_hash"], "errors": errors, "checks": receipts, "design": design_receipts}
    path = directory / "receipt.json"
    util.atomic_json(path, record)
    state["task_preflight"] = {**record, "receipt": str(path), "receipt_sha256": util.file_hash(path)}
    persist(Path(run_dir) / "state.json", state)
    if errors:
        if pause_requested():
            raise util.Paused('PAUSED_REQUESTED', 'Pause requested during prerequisite execution; no provider was dispatched')
        raise util.Paused("PAUSED_TASK_PREFLIGHT", f"{phase} prerequisite blocked before provider dispatch: " + "; ".join(errors))
