"""Generate the published provider conformance matrix (#706).

One table in docs/providers.md, from tools/provider-matrix.json. Engine,
version, transport, containment, visual profile, result, date and the commit
it ran on. A version the offline conformance suite has not been run against
is 'untested' — never guess.

    python tools/provider_matrix.py --write     # rewrite the table in docs/providers.md
    python tools/provider_matrix.py             # print the table
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MATRIX = Path(__file__).resolve().with_name("provider-matrix.json")
PROVIDERS = REPO / "docs" / "providers.md"
BEGIN = "<!-- BEGIN provider conformance matrix -->"
END = "<!-- END provider conformance matrix -->"

COLUMNS = ("engine", "version", "transport", "containment", "visual_profile", "result", "date", "commit", "note")


def load_rows(path=MATRIX):
    data = json.loads(Path(path).read_text())
    if data.get("schema_version") != 1:
        raise ValueError("provider-matrix.json schema_version must be 1")
    rows = data.get("rows")
    if not isinstance(rows, list) or not rows:
        raise ValueError("provider-matrix.json needs a nonempty rows array")
    for row in rows:
        missing = [key for key in COLUMNS if key not in row]
        if missing:
            raise ValueError(f"conformance row is missing {missing}: {row}")
    return rows


def markdown(rows) -> str:
    lines = [
        BEGIN,
        "",
        "Generated by `python tools/provider_matrix.py --write` from",
        "[tools/provider-matrix.json](../tools/provider-matrix.json). Do not edit by hand.",
        "A version the offline conformance suite has not been run against is",
        "`untested` — never guess. Run the suite with",
        "`python tools/provider_conformance.py --fake` (no model calls).",
        "",
        "| Engine | Version | Transport | Containment | Visual | Result | Date | Commit | Note |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| {} | {} | {} | {} | {} | {} | {} | `{}` | {} |".format(
                row["engine"],
                row["version"],
                row["transport"],
                row["containment"],
                row["visual_profile"],
                row["result"],
                row["date"],
                row["commit"],
                row["note"],
            )
        )
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def write_table(path=PROVIDERS, matrix=MATRIX) -> str:
    text = Path(path).read_text()
    block = markdown(load_rows(matrix))
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        text = text.rstrip() + "\n\n## Conformance matrix\n\n" + block + "\n"
    Path(path).write_text(text)
    return block


def status_for(engine: str, version: str, rows=None) -> dict | None:
    """The matrix row for an installed engine version, or None when untested."""
    rows = load_rows() if rows is None else rows
    for row in rows:
        if row["engine"] == engine and row["version"] == version:
            return row
    return None


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the table in docs/providers.md")
    args = parser.parse_args(argv)
    if args.write:
        write_table()
        print(f"wrote the conformance matrix into {PROVIDERS}")
    else:
        print(markdown(load_rows()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
