"""Generate the dated reliability table from saved sweep rows (#694).

Fake-provider rows and live-model rows are never mixed (RELIABILITY.md). Each
row names the master commit the sweep ran on. The table is produced by a
command, never edited by hand.

    python tools/reliability_table.py docs/reliability-sweeps.json > docs/reliability-table.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# One sweep: a dated, named campaign on one profile and one master commit.
COLUMNS = ("date", "profile", "master", "mode", "runs", "passed", "false_completions", "median_minutes", "note")


def load_rows(path) -> list[dict]:
    data = json.loads(Path(path).read_text())
    if not isinstance(data, list):
        raise ValueError("reliability sweeps must be a JSON list of rows")
    rows = []
    for row in data:
        missing = [
            key
            for key in ("date", "profile", "master", "mode", "runs", "passed", "false_completions", "note")
            if key not in row
        ]
        if missing:
            raise ValueError(f"sweep row is missing {missing}: {row}")
        if row["mode"] not in ("live", "fake"):
            raise ValueError(f"mode must be live or fake, not {row['mode']!r}")
        if row["false_completions"] < 0 or row["runs"] < 0 or row["passed"] < 0:
            raise ValueError(f"counts must be non-negative: {row}")
        if row["passed"] + row["false_completions"] > row["runs"]:
            raise ValueError(f"passed + false_completions exceed runs: {row}")
        rows.append({key: row.get(key) if key != "median_minutes" else row.get(key) for key in COLUMNS})
    return rows


def markdown(rows: list[dict]) -> str:
    """A dated table per mode, live first, then fake. Never mixes the two."""
    lines = [
        "# Reliability table",
        "",
        "Generated by `python tools/reliability_table.py docs/reliability-sweeps.json`.",
        "Do not edit by hand. See [RELIABILITY.md](../RELIABILITY.md) for what these",
        "numbers do and do not claim. A row names the master commit the sweep ran on.",
        "",
    ]
    for mode, title in (("live", "Live models"), ("fake", "Fake provider")):
        subset = [row for row in rows if row["mode"] == mode]
        if not subset:
            continue
        lines += [
            f"## {title}",
            "",
            "| Date | Profile | Master | Runs | Passed | False completions | Median (min) | Note |",
            "| --- | --- | --- | ---: | ---: | ---: | ---: | --- |",
        ]
        for row in subset:
            median = "" if row.get("median_minutes") is None else str(row["median_minutes"])
            lines.append(
                f"| {row['date']} | {row['profile']} | `{row['master']}` | "
                f"{row['runs']} | {row['passed']} | {row['false_completions']} | "
                f"{median} | {row['note']} |"
            )
        lines.append("")
    return "\n".join(lines)


def readme_excerpt(rows: list[dict]) -> str:
    """The short copy for the README: live rows only, one line each."""
    lines = [
        "",
        "## Reliability",
        "",
        "AutoCode does not report completion without evidence. Live sweeps on the",
        "three-case portfolio (small new application, feature in an existing project,",
        "bug fix) are recorded in [docs/reliability-table.md](docs/reliability-table.md)",
        "and [RELIABILITY.md](RELIABILITY.md). Fake-provider rows are kept separate",
        "and never mixed with these.",
        "",
        "| Date | Profile | Runs | Passed | False completions |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for row in rows:
        if row["mode"] != "live":
            continue
        lines.append(
            f"| {row['date']} | {row['profile']} | {row['runs']} | {row['passed']} | {row['false_completions']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sweeps", help="JSON list of sweep rows")
    parser.add_argument("--readme", action="store_true", help="print the README excerpt instead")
    args = parser.parse_args(argv)
    rows = load_rows(args.sweeps)
    print(readme_excerpt(rows) if args.readme else markdown(rows), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
