"""Generate the dated reliability table from saved sweep rows (#694).

Fake-provider rows and live-model rows are never mixed (RELIABILITY.md). Each
row names the master commit the sweep ran on. The table is produced by a
command, never edited by hand.

    python tools/reliability_table.py docs/reliability-sweeps.json > docs/reliability-table.md
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from statistics import median

try:
    from . import autocode_interaction_timing as interaction_timing
except ImportError:
    import autocode_interaction_timing as interaction_timing

# One sweep: a dated, named campaign on one profile and one master commit.
COLUMNS = (
    "date",
    "profile",
    "master",
    "prompts_hash",
    "mode",
    "runs",
    "passed",
    "false_completions",
    "median_minutes",
    "note",
    "interaction_timings",
)


def load_rows(path) -> list[dict]:
    data = json.loads(Path(path).read_text())
    if not isinstance(data, list):
        raise ValueError("reliability sweeps must be a JSON list of rows")
    rows = []
    for row in data:
        missing = [
            key
            for key in ("date", "profile", "master", "mode", "runs", "passed", "false_completions", "note")
            if key not in row
        ]
        if missing:
            raise ValueError(f"sweep row is missing {missing}: {row}")
        if row["mode"] not in ("live", "fake"):
            raise ValueError(f"mode must be live or fake, not {row['mode']!r}")
        if row["false_completions"] < 0 or row["runs"] < 0 or row["passed"] < 0:
            raise ValueError(f"counts must be non-negative: {row}")
        if row["passed"] + row["false_completions"] > row["runs"]:
            raise ValueError(f"passed + false_completions exceed runs: {row}")
        prompts_hash = row.get("prompts_hash")
        if prompts_hash is not None and (
            not isinstance(prompts_hash, str) or not re.fullmatch(r"[0-9a-f]{64}", prompts_hash)
        ):
            raise ValueError("prompts_hash must be a SHA-256 digest or unknown")
        samples = row.get("interaction_timings")
        if samples is not None:
            if not isinstance(samples, list):
                raise ValueError("interaction_timings must be a list of public timing samples")
            for sample in samples:
                if not isinstance(sample, dict) or not isinstance(sample.get("run"), str) or not sample["run"].strip():
                    raise ValueError("an interaction timing sample must name its run")
                launch = sample.get("launched_at")
                if interaction_timing.elapsed(launch, launch) != 0:
                    raise ValueError("an interaction timing sample needs an aware launch timestamp")
                projected = interaction_timing.project({"interaction_timing": sample})
                for event in interaction_timing.EVENTS:
                    at, seconds = f"first_{event}_at", f"first_{event}_seconds"
                    duration = sample.get(seconds)
                    if duration is not None and (isinstance(duration, bool) or not isinstance(duration, (int, float))):
                        raise ValueError(f"{event} elapsed seconds must be numeric or unknown")
                    if at not in sample or seconds not in sample or sample[seconds] != projected[seconds]:
                        raise ValueError(f"{event} timing must preserve the public timestamp and elapsed seconds")
                    if sample[at] is not None and projected[seconds] is None:
                        raise ValueError(f"{event} timestamp must be aware and no earlier than launch")
        rows.append({key: row.get(key) for key in COLUMNS})
    return rows


def markdown(rows: list[dict]) -> str:
    """A dated table per mode, live first, then fake. Never mixes the two."""
    lines = [
        "# Reliability table",
        "",
        "Generated by `python tools/reliability_table.py docs/reliability-sweeps.json`.",
        "Do not edit by hand. See [RELIABILITY.md](../RELIABILITY.md) for what these",
        "numbers do and do not claim. A row names the master commit the sweep ran on.",
        "",
    ]
    for mode, title in (("live", "Live models"), ("fake", "Fake provider")):
        subset = [row for row in rows if row["mode"] == mode]
        if not subset:
            continue
        lines += [
            f"## {title}",
            "",
            "| Date | Profile | Master | Prompts (SHA-256) | Runs | Passed | False completions | Median (min) | Note |",
            "| --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- |",
            "| Date | Profile | Master | Runs | Passed | False completions | Median (min) | First question (s) | First plan (s) | First Builder (s) | Note |",
            "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
        ]
        for row in subset:
            completion_median = "" if row.get("median_minutes") is None else str(row["median_minutes"])
            first = []
            for event in interaction_timing.EVENTS:
                known = [
                    sample[f"first_{event}_seconds"]
                    for sample in row.get("interaction_timings") or []
                    if sample.get(f"first_{event}_seconds") is not None
                ]
                first.append("" if not known else str(median(known)))
            lines.append(
                f"| {row['date']} | {row['profile']} | `{row['master']}` | "
                f"{row.get('prompts_hash') or 'not recorded'} | {row['runs']} | {row['passed']} | {row['false_completions']} | "
                f"{median} | {row['note']} |"
                f"{row['runs']} | {row['passed']} | {row['false_completions']} | "
                f"{completion_median} | {' | '.join(first)} | {row['note']} |"
            )
        lines.append("")
        samples = [(row, sample) for row in subset for sample in row.get("interaction_timings") or []]
        if samples:
            lines += [
                "### First interaction samples",
                "",
                "Times start at CLI main entry before workspace setup. They include human wait; Builder is job dispatch, not first model token. Medians above use recorded values only. Blank cells mean unrecorded or unreached.",
                "",
                "| Profile | Master | Run | Launched at | First question shown at | First plan shown at | First Builder dispatched at |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
            for row, sample in samples:
                events = []
                for event in interaction_timing.EVENTS:
                    at, seconds = sample[f"first_{event}_at"], sample[f"first_{event}_seconds"]
                    events.append("" if at is None else f"{at} ({seconds}s)")
                lines.append(
                    f"| {row['profile']} | `{row['master']}` | {sample['run']} | {sample['launched_at']} | {' | '.join(events)} |"
                )
            lines.append("")
    return "\n".join(lines)


def readme_excerpt(rows: list[dict]) -> str:
    """The short copy for the README: live rows only, one line each."""
    lines = [
        "",
        "## Reliability",
        "",
        "AutoCode does not report completion without evidence. Live sweeps on the",
        "three-case portfolio (small new application, feature in an existing project,",
        "bug fix) are recorded in [docs/reliability-table.md](docs/reliability-table.md)",
        "and [RELIABILITY.md](RELIABILITY.md). Fake-provider rows are kept separate",
        "and never mixed with these.",
        "",
        "| Date | Profile | Runs | Passed | False completions |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for row in rows:
        if row["mode"] != "live":
            continue
        lines.append(
            f"| {row['date']} | {row['profile']} | {row['runs']} | {row['passed']} | {row['false_completions']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sweeps", help="JSON list of sweep rows")
    parser.add_argument("--readme", action="store_true", help="print the README excerpt instead")
    args = parser.parse_args(argv)
    rows = load_rows(args.sweeps)
    print(readme_excerpt(rows) if args.readme else markdown(rows), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
