#!/bin/sh
# Builds the native Autocode macOS app: compile with SwiftPM, bundle into
# Autocode.app, and ad-hoc codesign. Run from anywhere: ./build-app.sh [checkout]
set -eu
cd "$(dirname "$0")"

CHECKOUT="${1:-$(cd .. && pwd)}"
APP="dist/Autopilot.app"
BUILD_LOG="${TMPDIR:-/tmp}/autocode-build-app-$$.log"
cleanup() { rm -f "$BUILD_LOG"; }
trap cleanup EXIT INT TERM

cat > Sources/Autocode/BuildConfig.swift <<EOF
// Generated by build-app.sh — the default Autocode checkout baked at build time.
// Overridable at runtime in the app's Settings; regenerated on every build.
enum BuildConfig {
    static let defaultCheckout = "$CHECKOUT"
}
EOF

# SwiftPM object files can go stale when two builds share .build (racy
# timestamps: "input file … was modified during the build"). Detect that and
# rebuild from scratch instead of failing the bundle step.
stale_objects() {
  grep -q 'was modified during the build\|timestamp mismatch' "$BUILD_LOG" 2>/dev/null
}

echo "Building Autocode.app (default checkout: $CHECKOUT)"
if ! swift build -c release >"$BUILD_LOG" 2>&1; then
  cat "$BUILD_LOG" >&2
  if stale_objects; then
    echo "Stale SwiftPM object files detected; clearing .build and retrying once." >&2
    rm -rf .build
    swift build -c release >"$BUILD_LOG" 2>&1 || { cat "$BUILD_LOG" >&2; exit 1; }
  else
    exit 1
  fi
fi
cat "$BUILD_LOG"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp .build/release/Autocode "$APP/Contents/MacOS/Autocode"
cp icon/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleExecutable</key><string>Autocode</string>
    <key>CFBundleIdentifier</key><string>com.autocode.macosapp</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>Autopilot</string>
    <key>CFBundleDisplayName</key><string>Autopilot</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundleIconName</key><string>AppIcon</string>
    <key>CFBundleShortVersionString</key><string>1.0.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSApplicationCategoryType</key><string>public.app-category.developer-tools</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSPrincipalClass</key><string>NSApplication</string>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsLocalNetworking</key><true/>
    </dict>
</dict>
</plist>
EOF

codesign --force --sign - "$APP" >/dev/null 2>&1 || codesign --force -s - "$APP"
echo "Built $APP"
echo "Run it with: open $APP"
