// Current checkpoint authority and chronological history, exercised with saved-state scenarios.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../dashboard_app.js'),'utf8');
const context=vm.createContext({URL,URLSearchParams});
vm.runInContext(source.slice(source.indexOf('const basename ='),source.indexOf("document.addEventListener('focusin'"))+source.slice(source.indexOf('function concise('),source.indexOf('function badge('))+source.slice(source.indexOf('function jointPlanning('),source.indexOf('function setView('))+source.slice(source.indexOf('function interruptedAttempt('),source.indexOf('function renderPrimaryAction('))+source.slice(source.indexOf('function messageTime('),source.indexOf('function icon('))+source.slice(source.indexOf('function taskMessages('),source.indexOf('function settleThreadScroll(')),context);
const approved={run:'/fixture/current',status:'PAUSED_REQUESTED',stage:'terra',iteration:16,goal:{revision:4,approval_status:'approved'},stages:[{stage:'terra'}],model_settings:{roles:{terra:'zai-coding-plan/glm-5.3'}},monitor:{next_stage:'terra',limits_known:true,iteration_limit:18,live:{state:'none'}},planning_messages:[{text:'Older draft needs approval',created_at:'2026-09-19T08:00:00Z'}]};
assert.equal(context.taskDecision(approved).title,'No approval pending');
assert.equal(context.taskDecision(approved).action.label,'Resume task');
assert.match(context.taskDecision(approved).after,/already|approved plan/);
assert.equal(context.taskPhase(approved),'implementation');
assert.equal(context.taskPosition(approved),'Plan r4 · approved  /  Iteration 16 of 18');
assert.equal(context.stageName(approved),'GLM · Implementing');
const running={...approved,status:'RUNNING',active_stage:{stage:'terra'},monitor:{...approved.monitor,live:{state:'alive'}}};
assert.equal(context.taskDecision(running).required,false);
assert.equal(context.taskDecision(running).action.kind,'pause');
const ready={status:'AWAITING_GOAL_APPROVAL',goal_token:'r5:current',goal:{revision:5,origin:'astra_finalize',approval_status:'draft'},model_settings:{joint_planning:true}};
assert.equal(context.taskDecision(ready).title,'Approve plan revision 5');
assert.equal(context.taskDecision(ready).required,true);
assert.match(context.taskDecision(ready).after,/records approval; Start building or Resume task/);
assert.equal(context.taskPhase(ready),'approval');
assert.equal(context.taskDecision({...ready,status:'RUNNING',stage:'glm_revise',active_stage:{stage:'glm_revise'},monitor:{live:{state:'alive'}},goal:{...ready.goal,origin:'glm_revise'}}).required,false);
assert.equal(context.taskDecision({...ready,status:'PAUSED_REQUESTED'}).required,false);
const question={...ready,status:'WAITING_FOR_USER',questions:[{id:'q1',question:'Which scope?'}]};
assert.equal(context.taskDecision(question).title,'Answer 1 question');
assert.equal(context.taskDecision(question).action.kind,'answer');
assert.equal(context.taskDecision({...ready},true).required,false);
const review={...approved,status:'WAITING_FOR_USER',user_request:{kind:'human_review'},review_token:'new-result',review_criteria:[{id:'R1',criterion:'Inspect output'}],human_reviews:{R1:{token:'old-result'}}};
assert.equal(context.taskDecision(review).title,'Review the finished work');
assert.equal(context.taskDecision({...review,human_reviews:{R1:{token:'new-result'}}}).title,'Your review is saved');
assert.equal(context.taskDecision({...approved,status:'TASK_COMPLETE'}).required,false);
const messages=context.taskMessages({draft_messages:[{text:'Initial idea',created_at:'2026-09-19T01:00:00Z'}],planning_messages:[{text:'Draft',created_at:'2026-09-19T02:00:00Z'},{text:'Revision',created_at:'2026-09-19T04:00:00Z'}],answers:{q1:{text:'Saved answer',at:'2026-09-19T03:00:00Z',question:{question:'Which scope?'}},q2:{text:'Duplicate receipt',at:'2026-09-19T05:00:00Z'}},chat_messages:[{text:'Latest answer',question_id:'q2',created_at:'2026-09-19T05:00:00Z'}]});
assert.deepEqual(Array.from(messages,m=>m.text),['Initial idea','Draft','Saved answer','Revision','Latest answer']);
assert.equal(messages[2].question_text,'Which scope?');
assert.equal(messages[1].planning_history,true);
console.log('Current approval authority, resume decisions, workflow phase, model identity, and conversation ordering passed.');
